# SPRINT3 TAREA1

## Exercici 1

***Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error***



In [6]:
import numpy as np

In [8]:
def estadísticaprevia(arr):
    if len(arr.shape) >1:
            print ('error')
    else:
        print (arr)
        print ('Dimensión del array:',arr.ndim)
        print ('Valor Mínimo:', np.min(arr))
        print ('Valor Máximo:', np.max(arr))
        print ('Media Aritmética:',np.mean(arr))
        print ('Valor equidistante de los extremos:', np.median (arr))
        print ('Desviación:', np.std(arr))


In [9]:
from numpy import random
arr5 =random.rand (40)
estadísticaprevia(arr5)

[0.39547442 0.72678495 0.13092793 0.37725425 0.12669987 0.73428923
 0.40308233 0.68883859 0.18446309 0.85086597 0.38177515 0.26093264
 0.38628031 0.23715368 0.14168877 0.26028882 0.2904823  0.34257865
 0.88897311 0.93327444 0.40933901 0.58939561 0.12138715 0.26279584
 0.36070196 0.24775345 0.79432059 0.41217039 0.01988374 0.22717204
 0.87584714 0.90340615 0.05140966 0.39294102 0.22230149 0.59701168
 0.6947348  0.01692182 0.90918627 0.46384284]
Dimensión del array: 1
Valor Mínimo: 0.01692181708128715
Valor Máximo: 0.9332744405002709
Media Aritmética: 0.4328657787382558
Valor equidistante de los extremos: 0.3840277303607047
Desviación: 0.27310345292707994


## Exercici 2

***Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.***



In [10]:
def TablaAleatoria():
    print ('TABLA ALEATORIA DE 0 A 100:')
    print (np.random.randint(100, size=(10,10)))

In [11]:
TablaAleatoria ()

TABLA ALEATORIA DE 0 A 100:
[[82  4 40 65 52  0 13 46 85 23]
 [60 10 77 70 37 79 93 47 69 13]
 [51 54 73 35  1 74 94 95 49 27]
 [91  3  1 45 72 55 51 42 46 80]
 [44  5 13 34 87 46 50 29 20  3]
 [27 72 56 58 78 39 33  5 77 92]
 [83 61 34 75 90 69 99  5 47 10]
 [55 32 43 44 25 36 97 99 87 87]
 [78 78 57 68 28 13 47 99 42 50]
 [27 42 37 81  9 21 59 67 81 54]]


## Exercici 3

***Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.***

In [12]:
def Totales (arr):
    print ('Suma por Filas:', np.sum(arr, axis=1))
    print ('Suma por Columnas:', np.sum(arr, axis=0))

In [13]:
arr1=np.random.randint(100, size=(7,8))
print (arr1)

[[45 89 82 59 44 38 23 45]
 [40 95 38 38 81  3 65 75]
 [55 75 46 32 90 83  6 67]
 [24 77 43 95 58 29 17 77]
 [92 55 20 46 48 78 65 58]
 [60 39 98 80 78 13 71 88]
 [18 10 85 38  1 43 60 66]]


In [14]:
Totales (arr1)

Suma por Filas: [425 435 454 420 462 527 321]
Suma por Columnas: [334 440 412 388 400 287 307 476]


## Exercici 4

***Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.***

In [15]:
arr1 = np.random.randint(100,size=20)
arr2 = np.random.randint(100, size=20)
print (arr1)
print (arr2)

[74 83  2 54 82 27 39 66 32 78 51 88 83 23 92 82 81 88 36 19]
[52 27 21 48 48 41 25 39 24 23 97 13 89 26 43 17 27 22  8 29]


In [25]:
                                       #1er    Obtenir la covariança en tres passes:
producto=arr1*arr2                                  #    -Fer el producte entre les mostres de dades...         
pre_cov=sum(producto)/len(arr1)                     #    -...dividit pel número de mostres respectives
prod_medias=np.mean(arr1)*np.mean(arr2)                          #(Producte de mitges aritmétiques)
covarianza = pre_cov - prod_medias                  #     -...resultat del qual es resta el producte de les mitges aritmétiques, obtingut al pas anterior
stds = np.std(arr1)*np.std(arr2)                                #(Producte de les respectives desviacions)
coeficiente = covarianza/stds          #2on    Divisió de la covariança pel producte de les desviacions. El resultat és el coeficient de correlació
print (coeficiente)                           
pearson= np.corrcoef(arr1,arr2)             #Comprovació amb la funció incorporada a numpy...
print (pearson)


0.15050468770394743
[[1.         0.15050469]
 [0.15050469 1.        ]]


In [28]:
                                                          #La funció...
def Coef_correlacion(arr1,arr2):
    pre_cov=sum(arr1*arr2)/len(arr1)
    covarianza=pre_cov-(np.mean(arr1)*np.mean(arr2))
    coef=covarianza/(np.std(arr1)*np.std(arr2))
    print (coef)
Coef_correlacion (arr1,arr2)                             

0.15050468770394743


In [34]:
                                 #En una línia, ja que és una pura fórmula matemàtica. Ara, molt 'pithònic' crec que no queda...
def Correlacion(arr1,arr2):
    print (((sum(arr1*arr2)/len(arr1))-(np.mean(arr1)*np.mean(arr2)))/(np.std(arr1)*np.std(arr2)))


In [35]:
Correlacion (arr1, arr2)

0.15050468770394743
